version: "3"
services:
  postgres:
    image: "postgres:latest"
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "80:80"
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./activity5-backend
      # context: "./server"
    depends_on:
      - postgres
    volumes:
      - /app/node_modules
      - ./activity5-backend:/app
    env_file:
      - ./activity5-backend/.env
    # environment:
    #   - PGUSER=postgres
    #   - PGHOST=postgres
    #   - PGDATABASE=postgres
    #   - PGPASSWORD=password
    #   - PGPORT=5432
  client:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile.dev
      context: ./activity5-frontend
      # context: ./client
    volumes:
      - /app/node_modules
      - ./activity5-frontend:/app
